packages:
  - apps/dev
  - packages/core
  - packages/maplibre
  - packages/mapbox

minimumReleaseAge: 10080

overrides:
  ajv: 6.14.0

allowBuilds:
  '@parcel/watcher': true
  svelte-preprocess: true
